apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-1

manageNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 3
    spot: true
   